--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: ecommerce-akmal
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255),
    price double precision NOT NULL
);


ALTER TABLE public.product OWNER TO "ecommerce-akmal";

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce-akmal
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: ecommerce-akmal
--

COPY public.product (id, description, name, price) FROM stdin;
1	asdas	dsfds	21111
2	pkmfmkew	jnbf	23000
3	ara	ara	21101
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce-akmal
--

SELECT pg_catalog.setval('public.product_id_seq', 3, true);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce-akmal
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

