version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile_product
    container_name: product-service
    ports:
      - "${SERVICE_HOST}:8081"
    environment:
      SERVICE_HOST: "${SERVICE_HOST}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      EUREKA_HOST: "${EUREKA_HOST}"
    networks:
      - db-ecommerce-net
    restart: always
    depends_on:
      - db-ecommerce-akmal

networks:
  db-ecommerce-net:
    external: true