server:
  port: 8082  # Make sure it's unique per service

spring:
  application:
    name: operations-service  # This is important for Eureka registration

  datasource:
    url: jdbc:postgresql://localhost:5000/ecommerce_akmal
    username: ecommerce-akmal
    password: akmal2121234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # "validate", "create", "create-drop", or "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false  # helpful for development

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
