name: Deploy Eureka Server

on:
  push:
    branches:
      - publish
    paths:
      - 'eureka-server/**'  # Only trigger when something in eureka-server changes

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eureka-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests
        run: ./mvnw test

      - name: Build and run Docker container
        run: docker-compose --project-name "eureka-server" -f ./builder/docker-compose.yml up --build -d
