name: Deploy Eureka Server

on:
  push:
    branches:
      - publish
    paths:
      - 'eureka-server/**'  # Only trigger when something in eureka-server changes

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eureka-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            echo "Starting build"
            cd /home/azureuser/ecommerce_builder/eureka-server
            docker-compose --project-name "eureka-server" -f ./docker-compose-eureka.yml up --build -d